window.STUDIO_I18N = (() => {
  const KEY = 'arena_studio_lang_v081';
  const entityDict = {
    profession: { warrior:'Warrior', mage:'Mage', rogue:'Rogue', priest:'Priest', shaman:'Shaman', necro:'Necromancer', warlock:'Warlock', swordsman:'Swordsman', hunter:'Hunter' },
    weapon: { greatsword:'Greatsword', longbow:'Longbow', dagger:'Dagger', warhammer:'Warhammer', wand:'Wand', twin_blades:'Twin Blades', totem:'Totem' },
    accessory: { lincoln:'Linken Sphere', trapbag:'Trap Bag', hope:'Dawn of Hope', blood_phial:'Blood Phial', time_rewind:'Time Rewind', void_core:'Void Core', holy_icon:'Holy Icon' },
    origin: { '职业技能':'Class Skill', '武器技能':'Weapon Skill', '饰品技能':'Accessory Skill', '职业被动':'Class Passive', '负面牌':'Negative Card' },
    template: { direct_damage:'Direct Damage', self_buff:'Self Buff', teleport:'Teleport', aoe:'Area Damage', dash_hit:'Dash Hit', dual_mode:'Dual Mode', insert_negative_card_into_target_deck:'Insert Negative Card', mark_target_for_bonus:'Mark Target', bonus_if_target_marked:'Marked Bonus', summon_token_into_self_deck:'Summon Token', consume_all_activated_tokens_for_burst:'Undead Burst', hunter_trap:'Hunter Trap', hunter_command:'Kill Command', hunter_volley:'Volley', priest_sanctuary:'Sanctuary', priest_judgement:'Judgement', shaman_chain:'Chain Lightning', shaman_spiritwalk:'Spirit Walk', necro_gravebind:'Gravebind', necro_legion:'Undead Legion', lock_bloodpact:'Blood Pact', lock_doom:'Doom', sword_focus:'Mind Eye' }
  };
  const ui = {
    zh: { lang_zh:'中文', lang_en:'English', index_title:'无限制角斗场 Studio v0.8.3', index_sub:'以 v0.7.9 稳定框架为基线，补回后续职业、饰品、地图与双语切换。', rulesets:'规则副本', duplicate_current:'复制当前副本', rename:'重命名', delete_current:'删除当前副本', open_editor:'打开模板编辑器', enter_game:'进入游戏', index_hint:'当前重点：保留 v0.7.9 的行动经济和地图框架，在其上追加新职业、新武器、新饰品与双语切换。', editor_title:'模板编辑器 v0.8.3', editor_sub:'沿用稳定模板编辑器框架，并补回后续内容。', ruleset:'规则副本', edit_scope:'编辑对象', profession:'职业', entry:'条目', class_cards:'职业卡', class_passives:'职业被动', new_entry:'新建条目', duplicate_entry:'复制当前条目', delete_entry:'删除当前条目', save_entry:'保存当前条目', save_ruleset:'保存整个规则副本', template_info:'模板信息', attached_status:'附带状态模板', form_area:'表单编辑区', reset_original:'恢复原始值', live_preview:'实时预览', game_title:'游戏本体 v0.8.3', game_sub:'读取当前规则副本，保留稳定行动经济，并补回新职业、新饰品和双语切换。', p1_prof:'玩家 1 职业', p1_weapon:'玩家 1 武器', p1_accessory:'玩家 1 饰品', p2_type:'玩家 2 类型', human:'人类', ai:'电脑', p2_prof:'玩家 2 职业', p2_weapon:'玩家 2 武器', p2_accessory:'玩家 2 饰品', start_game:'开始游戏', back_home:'返回首页', battle_log:'战斗日志', current_mode:'当前模式：待机', move_mode:'移动模式', basic_attack:'普通攻击', cancel:'取消选择', end_turn:'结束回合', restart:'重新开局', current_hand:'当前手牌', waiting:'等待开始', select_action:'请选择一个动作。' },
    en: { lang_zh:'中文', lang_en:'English', index_title:'Arena Studio v0.8.3', index_sub:'Built on the stable v0.7.9 framework, with later professions, accessories, map size, and bilingual switching restored.', rulesets:'Rulesets', duplicate_current:'Duplicate Current', rename:'Rename', delete_current:'Delete Current', open_editor:'Open Template Editor', enter_game:'Enter Game', index_hint:'Current focus: keep the stable v0.7.9 action economy and map framework, then layer new professions, weapons, accessories, and bilingual UI on top.', editor_title:'Template Editor v0.8.3', editor_sub:'Keeps the stable editor framework and restores later content.', ruleset:'Ruleset', edit_scope:'Edit Scope', profession:'Profession', entry:'Entry', class_cards:'Class Cards', class_passives:'Class Passives', new_entry:'New Entry', duplicate_entry:'Duplicate Entry', delete_entry:'Delete Entry', save_entry:'Save Entry', save_ruleset:'Save Ruleset', template_info:'Template Info', attached_status:'Attached Status Template', form_area:'Form Editor', reset_original:'Reset Original', live_preview:'Live Preview', game_title:'Game v0.8.3', game_sub:'Reads the active ruleset, keeps the stable action economy, and restores new professions, accessories, and bilingual switching.', p1_prof:'P1 Profession', p1_weapon:'P1 Weapon', p1_accessory:'P1 Accessory', p2_type:'P2 Type', human:'Human', ai:'AI', p2_prof:'P2 Profession', p2_weapon:'P2 Weapon', p2_accessory:'P2 Accessory', start_game:'Start Game', back_home:'Back Home', battle_log:'Battle Log', current_mode:'Mode: Idle', move_mode:'Move Mode', basic_attack:'Basic Attack', cancel:'Cancel', end_turn:'End Turn', restart:'Restart', current_hand:'Current Hand', waiting:'Waiting', select_action:'Choose an action.' }
  };
  function getLang(){ return localStorage.getItem(KEY) || 'zh'; }
  function setLang(lang){ localStorage.setItem(KEY, lang); window.dispatchEvent(new Event('studio-language-changed')); applyPage(); }
  function t(key, fallback=''){ const lang=getLang(); return (ui[lang] && ui[lang][key]) || fallback || key; }
  function entity(type, key, fallback=''){ const lang=getLang(); if(lang==='zh') return fallback || key; return (entityDict[type] && entityDict[type][key]) || fallback || key; }
  function applyPage(){
    const lang=getLang();
    document.documentElement.lang = lang === 'en' ? 'en' : 'zh-CN';
    document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent=t(el.dataset.i18n, el.textContent); });
    document.querySelectorAll('[data-i18n-title]').forEach(el=>{ document.title=t(el.dataset.i18nTitle, document.title); });
    document.querySelectorAll('[data-lang-btn]').forEach(btn=>{ btn.classList.toggle('secondary', btn.dataset.langBtn===lang); });
  }
  document.addEventListener('DOMContentLoaded', ()=>{ document.querySelectorAll('[data-lang-btn]').forEach(btn=>btn.onclick=()=>setLang(btn.dataset.langBtn)); applyPage(); });
  return { getLang, setLang, t, entity, applyPage };
})();